services:
  postgres:
    image: postgres:13
    container_name: graphql_project_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - graphql_project_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphql_project_app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_USER}@postgres:5432/${DB_NAME}?sslmode=disable
    depends_on:
      - postgres
    networks:
      - graphql_project_network

volumes:
  postgres_data:

networks:
  graphql_project_network:
    driver: bridge
